### ISSUE TITLE
Can't extract the exe

### ISSUE THREAD

**Issue by Tobe2d** [Sharrnah/whispering-ui#1]
I can't extract the exe file it show me this:

![image](https://user-images.githubusercontent.com/4099839/215343441-6d36e791-738b-4af6-8501-13881a7b663a.png)

And when I click on Continue it show this:

![image](https://user-images.githubusercontent.com/4099839/215343519-7dd91dd2-6048-49c8-9683-d65deafc334a.png)

I tested it in few folders and all give same issue however any other exe extraction from zip work flawlessly.

**Comment by Sharrnah** [comment]
Thats strange.

It sounds as if something is deleting the exe immediately after you extracted it.

Can you check if maybe some antivirus is deleting it for some reason?

I also just checked if there is any antivirus detecting something, but it doesn't show any.

https://www.virustotal.com/gui/file/63c6ac90fc4ffdb581104e37b0f1136e1648ca44fd57e18374535e5c64d5e04e

Are you first extracting it to somewhere and then executing, or executing it directly from inside the zip file?

**Comment by Tobe2d** [comment]
You are right,
<img width="861" alt="image" src="https://user-images.githubusercontent.com/4099839/215443806-d61789d8-6e8c-47ca-889a-df9bf042a6d2.png">


But why?

**Comment by Sharrnah** [comment]
I would say this is most likely a false alarm caused by some antivirus heuristic.

according to the class list of Kaspersky, it can be classified as this:
- Downloads and installs new versions of programs.
  -  _Yes this is what Whispering Tiger can do if a new version is found._
- the programs are launched or included on a list of programs which run automatically. 
  - _The new version of the UI can be launched right after update if you choose so._
- This type of malicious program is frequently used in the initial infection of visitors to websites which contain exploits.
  - _Well. its available from GitHub where basically everyone can provide downloads to programs._

I can only say that it is very very likely only a false alarm and i would appreciate it if you could somehow send Kaspersky the hint that this is a false alarm (if that is possible).

If you are hesitant to use the application i can understand it. You still have the option to use the python code directly from https://github.com/Sharrnah/whispering

the UI runs the same python code in the background. It just provides a more convenient way to download, update, interact and use it.

I will see if i can do something about it, but i fear this will be nearly impossible without removing some functionality like that the Application can update itself.

**Comment by Tobe2d** [comment]
Thanks a lot of the explanation.

I pused Kaspersky and extracted it however once I open it... it removed it immediately... and do restart and its kind of anoying as I cant even get to the point to excude the file from it.

Hopeyou will find solution for this.

Best Regards

**Comment by Sharrnah** [comment]
@Tobe2d I made a new release where i removed the In-Place update of the application.
https://github.com/Sharrnah/whispering-ui/releases/latest

Instead it will now send you directly to the GitHub Release Page.

![image](https://user-images.githubusercontent.com/55756126/215498377-906be8da-8445-44f5-ba10-dfa966043c28.png)

I hope this solves the false positive.

**Comment by Sharrnah** [comment]
In addition, Kaspersky just told me they will fix the false positive.

So one way or another, i would say this should be solved.

**Comment by Tobe2d** [comment]
Thank you @Sharrnah 

Yes! now it is working and now the update in progress... Cant wait to test it out ;-)

**Comment by trrahul** [comment]
Windows defender is also detecting it as malware.
![image](https://github.com/Sharrnah/whispering-ui/assets/7353840/e9576863-e588-4d99-85d4-a8a8cc80ddb8)

**Comment by Sharrnah** [comment]
Thanks. reported it to Microsoft. lets hope they are willing to solve this.

Edit: Actually currently it looks like its not detected by Microsoft Defender.

What Windows Version are you using, and is it the latest Defender Version?

And is it really the UI .exe or some file in the by the UI downloaded files?

**Comment by trrahul** [comment]
I am using windows 10. It flagged the file when I downloaded it.

**Comment by Sharrnah** [comment]
@trrahul
Here the report of the submission to microsoft of the application.
They don't seem to recognize it as malware or unwanted application.

![Screenshot 2023-06-10 153235](https://github.com/Sharrnah/whispering-ui/assets/55756126/d4ede998-62b8-42b2-8f19-03b87788a5b9)

So not really sure why it would flag it on your side.

If you want you can submit it yourself here:
https://www.microsoft.com/en-us/wdsi/filesubmission
