### ISSUE TITLE
cannot access local variable

### ISSUE THREAD

**Issue by DRIVER1ksa** [Sharrnah/whispering-ui#17]
![1111](https://github.com/Sharrnah/whispering-ui/assets/9286120/f03c4725-5f94-4cb8-878e-75c79e6cc09e)

**Comment by Sharrnah** [comment]
Thank you for reporting.

Do you have Voice Activity Detection Enabled or Disabled?

I would say it must be enabled as otherwise it would not try to access the vad_model.
But that would mean it was unable to load the model.

Can you provide the Log? You can find the Log under `Advanced -> Logs`

If it failed to load, it should show a line `Error loading vad model.`
and right below that, the actual error.

**Comment by DRIVER1ksa** [comment]
"Do you have Voice Activity Detection Enabled or Disabled?" yes

i just moved the folder to C drive. and everything now is working. thanks for your quick response.
