### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by funnymonkejuice** [Sharrnah/whispering-ui#3]
every time i open it it asks for me to update it and its not saving the update.

**Comment by Sharrnah** [comment]
i replied to you here https://github.com/Sharrnah/whispering/issues/8 already.
But since i think its just an issue about how the UI works, i explain it here again (just please try to only open a single issue about the same thing next time.):

If you are using the UI, if you are starting it for the first time, it will ask for an update of the Python Backend, because it does not have it yet. (And if you have downloaded it manually, it does not know about it).

So to use it, you need to confirm the update question and wait for the download to finish.
After that, you can create a Profile with settings that fit your PC (you are free to ask about help here maybe in a seperate issue.)
If you scroll down at the profile window, click on "Save and Load Profile".

It will start the Python Backend in the background, The Backend will download some AI models depending on the settings you choose, so this might take some time again unfortunately. But here you can close the waiting window and see in _Advanced -> Log_ what it is currently doing.

I hope that helps a bit.

---

It might also ask for a UI update before the Backend Update, Since an auto-update might trigger false-positives of anti-virus software, you need to download the UI manually from the github release. The info-box in the app will get you directly to that page.

**Comment by Sharrnah** [comment]
i will close this for now.
Feel free to open a new issue if you continue having issues.
